# https://aka.ms/yaml

trigger:
- v2

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: echo 'Adding env variables...'
  env:
    CHROMEWEBDRIVER: $(CHROMEWEBDRIVER)

- task: Npm@1
  name: 'NpmInstall'
  inputs:
    command: 'install'
    workingDir: 'src/frontend'

- task: Npm@1
  name: 'NpmLint'
  inputs:
    command: 'custom'
    workingDir: 'src/frontend'
    customCommand: 'run lint'

- task: Npm@1
  name: 'NpmBuild'
  inputs:
    command: 'custom'
    workingDir: 'src/frontend'
    customCommand: 'run build'

- task: Npm@1
  name: 'NpmTest'
  inputs:
    command: 'custom'
    workingDir: 'src/frontend'
    customCommand: 'run test -- --watch=false'